server: 
  port: 8082
  servlet: 
    context-path: /resource-server-opaque

####### resource server configuration properties
spring:
  security:
    oauth2:
      resourceserver:
        opaque:
          introspection-uri: http://localhost:8083/auth/realms/baeldung/protocol/openid-connect/token/introspect
          introspection-client-id: barClient
          introspection-client-secret: barClientSecret
          